JFLAGS = -g
JC = javac
JVM= java
DIR= src/edu/drexel/assignment1/
CLASSPATH= edu.drexel.assignment1

program1:
	$(JC) -d . $(DIR)Program1.java
	$(JVM) $(CLASSPATH).Program1

program2:
	$(JC) -d . $(DIR)Program2.java
	$(JVM) $(CLASSPATH).Program2

program3:
	$(JC) -d . $(DIR)Program3.java
	$(JVM) $(CLASSPATH).Program3

clean:
	$(RM) *.class